name: Media Player SDK .Net 6
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      Solution_Name: "Media Player SDK/VisioForge.MediaPlayer.Demos.CS (NuGet) net6.sln"
      Solution_Name_2: "Media Player SDK/VisioForge.MediaPlayer.Demos.CS net6.sln"
    
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET 
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: | 
          6.0.x
          
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-prerelease: true
        
    - name: Restore dependencies 1
      run: dotnet restore $env:Solution_Name

    - name: Build app for release 1
      run: msbuild $env:Solution_Name -t:rebuild -verbosity:diag -property:Configuration=Release

    - name: Restore dependencies 2
      run: dotnet restore $env:Solution_Name_2

    - name: Build app for release 2
      run: msbuild $env:Solution_Name_2 -t:rebuild -verbosity:diag -property:Configuration=Release  

#    - name: Build
#      run: dotnet build --no-restore _SOURCE\VisioForge.MediaFramework.Solution.sln
#    - name: Test
#      run: dotnet test --no-build --verbosity normal
