name: Media Blocks SDK .Net Console
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      Solution_Name_CS: "Media Blocks SDK/VisioForge.MediaBlocks.Demos.CS Console.sln"
    
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: | 
          3.1.x
          5.0.x
          6.0.x        
          
    - name: Setup .NET Framework
      uses: actions/setup-dotnet@v1      
          
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
        
    - name: Restore dependencies CS
      run: dotnet restore $env:Solution_Name_CS

    - name: Build app for release CS
      run: msbuild $env:Solution_Name_CS -t:rebuild -verbosity:diag -property:Configuration=Release

#    - name: Build
#      run: dotnet build --no-restore _SOURCE\VisioForge.MediaFramework.Solution.sln
#    - name: Test
#      run: dotnet test --no-build --verbosity normal
