name: Media Blocks SDK .Net Android
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      Solution_Name: "Media Blocks SDK/VisioForge.MediaBlocks.Demos.CS Android.sln"
    
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET 
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: | 
          6.0.x
          
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-prerelease: true
        
    - name: Install Android workload
      run: dotnet workload install android
        
    - name: Restore dependencies
      run: dotnet restore $env:Solution_Name

    - name: Build app for release
      run: msbuild $env:Solution_Name -t:rebuild -verbosity:diag -property:Configuration=Release
