name: Video Capture SDK .Net 5
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      Solution_Name_1: "Video Capture SDK/VisioForge.VideoCapture.Demos.CS (NuGet) net5.sln"
      Solution_Name_2: "Video Capture SDK/VisioForge.VideoCapture.Demos.CS.Avalonia (NuGet) net5.sln"
      Solution_Name_3: "Video Capture SDK/VisioForge.VideoCapture.Demos.CS.CV net5.sln"
    
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET 
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: | 
          5.0.x
          
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
        
    - name: (MAIN) Restore dependencies
      run: dotnet restore $env:Solution_Name_1

    - name: (MAIN) Build app for release
      run: msbuild $env:Solution_Name_1 -t:rebuild -verbosity:diag -property:Configuration=Release

    - name: (Avalonia) Restore dependencies
      run: dotnet restore $env:Solution_Name_2

    - name: (Avalonia) Build app for release
      run: msbuild $env:Solution_Name_2 -t:rebuild -verbosity:diag -property:Configuration=Release

    - name: (CV) Restore dependencies
      run: dotnet restore $env:Solution_Name_3

    - name: (CV) Build app for release
      run: msbuild $env:Solution_Name_3 -t:rebuild -verbosity:diag -property:Configuration=Release

#    - name: Build
#      run: dotnet build --no-restore _SOURCE\VisioForge.MediaFramework.Solution.sln
#    - name: Test
#      run: dotnet test --no-build --verbosity normal
