name: Video Edit SDK X .Net 7
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      Solution_Name: "Video Edit SDK X (crossplatform)/VisioForge.VideoEdit.X.Demos.CS.WinForms net7.sln"
      Solution_Name_2: "Video Edit SDK X (crossplatform)/VisioForge.VideoEdit.X.Demos.CS.Avalonia.sln"
    
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET 
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: | 
          7.0.x
          
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-prerelease: true
        
    - name: Restore dependencies
      run: dotnet restore $env:Solution_Name

    - name: Build app for release
      run: msbuild $env:Solution_Name -t:rebuild -verbosity:diag -property:Configuration=Release
      
    - name: Restore dependencies 2
      run: dotnet restore $env:Solution_Name_2

    - name: Build app for release 2
      run: msbuild $env:Solution_Name_2 -t:rebuild -verbosity:diag -property:Configuration=Release
