name: Video Edit SDK .Net 5
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      Solution_Name: "Video Edit SDK/VisioForge.VideoEdit.Demos.CS (NuGet) net5.sln"
    
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET 
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: | 
          5.0.x
          
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
        
    - name: Restore dependencies
      run: dotnet restore $env:Solution_Name

    - name: Build app for release
      run: msbuild $env:Solution_Name -t:rebuild -verbosity:diag -property:Configuration=Release

#    - name: Build
#      run: dotnet build --no-restore _SOURCE\VisioForge.MediaFramework.Solution.sln
#    - name: Test
#      run: dotnet test --no-build --verbosity normal
