name: Video Capture SDK .Net WinUI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      Solution_Name: "Video Capture SDK/VisioForge.VideoCapture.Demos.CS WinUI.sln"
    
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET 
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: | 
          6.0.x
          
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-prerelease: true
        
    - name: Restore dependencies
      run: dotnet restore $env:Solution_Name

    - name: Build app for release
      run: dotnet build -f net6.0-windows10.0.19041.0 -c Release -p:Platform=x64 --self-contained $env:Solution_Name 
